-- ============================================================================
-- Migration: payment_methods v1 — evolve from string[] to JSONB object array
-- ----------------------------------------------------------------------------
-- Evolves users.payment_methods from a bare string array (v0: ["qris","gopay"])
-- to a structured JSONB array of payment-method objects (v1).
--
-- Data model (v1 object shape):
--   {
--     "id":              "pm_<uuid>",           -- immutable, generated by backend
--     "type":            "bank" | "gopay" | "ovo" | "dana" |
--                        "shopeepay" | "linkaja" | "qris" |
--                        "bca" | "mandiri" | "bni" | "bri" |
--                        "cimb" | "permata",
--     "label":           "BCA Utama",           -- user-defined display name
--     "account_number":  "1234567890",          -- bank: 6-20 digits; null for e-wallet
--     "holder_name":     "Ricky Felix",         -- bank: account holder; null for e-wallet
--     "phone":           "628123456789",        -- e-wallet: phone number; null for bank/qris
--     "qris_image_path": "users/uuid/qris/…",  -- optional QRIS image path (Phase 4)
--     "is_primary":      true,
--     "created_at":      "2026-06-08T10:00:00Z",
--     "updated_at":      "2026-06-08T10:00:00Z"
--   }
--
-- Backward compatibility:
--   v0 data (["qris","gopay"]) coexists unchanged in the column; it is
--   detected and handled by the backend service (auto-convert on read/write)
--   and by the frontend (migration banner on next edit).
--   No destructive transformation is run here — no existing rows are mutated.
--
-- HOW TO APPLY:
--   Supabase Dashboard → SQL Editor → New query → paste → Run.
--   Idempotent: safe to run multiple times.
-- ============================================================================

-- ─────────────────────────────────────────────────
-- 1. Column comment update (cosmetic, no data change)
-- ─────────────────────────────────────────────────
COMMENT ON COLUMN users.payment_methods IS
  'v1: Array of payment-method objects — '
  '{ id, type, label, account_number, holder_name, phone, qris_image_path, is_primary, created_at, updated_at }. '
  'v0 legacy: bare string IDs (["qris","gopay","bca"]); auto-converted to v1 on next edit by the backend. '
  'NEVER holds, routes, or escrows funds — directory only (PDP / Bank Indonesia compliance).';

-- ─────────────────────────────────────────────────
-- 2. Ensure default is set (idempotent; harmless if already set)
-- ─────────────────────────────────────────────────
ALTER TABLE users
  ALTER COLUMN payment_methods SET DEFAULT '[]'::jsonb;

-- ─────────────────────────────────────────────────
-- 3. RLS: allow co-members to SELECT the users row
--    (masking of sensitive fields is done in the NestJS service layer,
--     not in SQL, because Postgres cannot partially mask JSONB fields
--     within a standard SELECT policy without a generated column or view)
-- ─────────────────────────────────────────────────

-- Helper: returns TRUE if the calling auth user is a co-member of target_user_id
-- in at least one group.  SECURITY DEFINER to avoid recursive RLS.
CREATE OR REPLACE FUNCTION public.is_group_co_member(target_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM group_members gm1
    JOIN group_members gm2
      ON gm1.group_id = gm2.group_id
    WHERE gm1.user_id = auth.uid()
      AND gm2.user_id = target_user_id
      AND gm1.user_id <> gm2.user_id  -- exclude self-match when same user
  );
$$;

-- Drop the old narrow "own-only" SELECT policy and replace it with one that
-- also allows group co-members to read the row (field masking stays in NestJS).
DROP POLICY IF EXISTS "users_select_own" ON users;
DROP POLICY IF EXISTS "users_select_peer" ON users;

CREATE POLICY "users_select_own_or_peer"
  ON users
  FOR SELECT
  USING (
    auth.uid() = id                      -- owner sees their own row
    OR public.is_group_co_member(id)     -- group co-member can read the row
    OR public.is_super_admin()           -- super_admin sees everything
  );

-- ─────────────────────────────────────────────────
-- 4. Storage bucket declaration (informational comment)
--    Actual bucket creation must be done via Supabase Dashboard:
--      Storage → New Bucket → "payment-qris-codes" → Private
--    Or via the Supabase Management API / CLI.
-- ─────────────────────────────────────────────────

-- NOTE: The "payment-qris-codes" bucket for QRIS image uploads (Phase 4) must be
-- created as a PRIVATE bucket in Supabase Storage. Path format per image:
--   users/{userId}/qris/{methodId}.{jpg|png}
-- Access is via signed URLs (1-hour expiry) issued by the NestJS storage endpoint.
-- This migration does not create the bucket; it must be created manually or via CLI.
