// ── Sample card data (matches the prototype) ──────────────────────────────────
//
// `status` is the deadline lifecycle, used by the home-deck filters:
//   "upcoming" — has a future due date, not pressing
//   "soon"     — nearing the deadline (drives the urgent/red treatment)
//   "overdue"  — deadline already passed (also urgent/red)
// Completed items use `settled: true` instead of a status.
//
// Cards carry the urgent badge whenever status is "soon" or "overdue" so the
// chip, gradient and CTA styling stay consistent with the deadline state.
export const ALL_CARDS = [
  {
    id: "card0",
    type: "arisan",
    status: "soon",
    eyebrow: "Arisan · Keluarga Sari · Giliran Budi S.",
    amount: "Rp 200.000",
    due: "Jatuh tempo 10 Jun",
    progress: 67,
    progressLabel: ["8/12 setor", "Putaran 6/12"],
    urgent: "2 hari lagi",
    badgeLabel: "Arisan",
    ctaLabel: "Bayar Sekarang",
    ctaType: "pay",
    destName: "Dompet Grup Keluarga Sari",
    destType: "arisan",
  },
  {
    id: "card1",
    type: "arisan",
    status: "upcoming",
    eyebrow: "Arisan · Arisan Kantor · Giliran Ana N.",
    amount: "Rp 150.000",
    due: "Jatuh tempo 15 Jun",
    progress: 25,
    progressLabel: ["2/8 setor", "Putaran 2/8"],
    urgent: null,
    badgeLabel: "Arisan",
    ctaLabel: "Bayar Sekarang",
    ctaType: "pay",
    destName: "Dompet Grup Arisan Kantor",
    destType: "arisan",
  },
  {
    id: "card2",
    type: "arisan",
    status: "soon",
    eyebrow: "Arisan · Arisan RT 05 · Giliran Pak Joko",
    amount: "Rp 50.000",
    due: "Jatuh tempo 8 Jun",
    progress: 15,
    progressLabel: ["3/20 setor", "Putaran 3/20"],
    urgent: "3 hari lagi",
    badgeLabel: "Arisan",
    ctaLabel: "Bayar Sekarang",
    ctaType: "pay",
    destName: "Dompet Grup Arisan RT 05",
    destType: "arisan",
  },
  {
    id: "card3",
    type: "patungan",
    status: "upcoming",
    eyebrow: "Patungan · Makan Bali · 3 belum bayar",
    amount: "Rp 270.000",
    due: "belum masuk dari 3 orang",
    progress: 60,
    progressLabel: ["3/6 sudah bayar", "60% lunas"],
    urgent: null,
    badgeLabel: "Patungan",
    ctaLabel: "Ingatkan 3 Teman",
    ctaType: "remind",
    reminderCount: 3,
    destName: null,
    destType: "patungan",
  },
  {
    id: "card4",
    type: "patungan",
    status: "soon",
    eyebrow: "Patungan · Hotel Bromo · 3 belum bayar",
    amount: "Rp 900.000",
    due: "kurang · 3 dari 4 belum bayar",
    progress: 25,
    progressLabel: ["1/4 sudah bayar", "25% lunas"],
    urgent: "Deadline 3 hari",
    badgeLabel: "Patungan",
    ctaLabel: "Tagih Sekarang",
    ctaType: "collect",
    reminderCount: 3,
    destName: null,
    destType: "patungan",
  },
  {
    id: "card8",
    type: "patungan",
    status: "overdue",
    eyebrow: "Patungan · Trip Yogya · 2 belum bayar",
    amount: "Rp 360.000",
    due: "Lewat tenggat · 3 Jun",
    progress: 50,
    progressLabel: ["2/4 sudah bayar", "50% lunas"],
    urgent: "Telat 2 hari",
    badgeLabel: "Patungan",
    ctaLabel: "Tagih Sekarang",
    ctaType: "collect",
    reminderCount: 2,
    destName: null,
    destType: "patungan",
  },
  {
    id: "card7",
    type: "arisan",
    status: "overdue",
    eyebrow: "Arisan · Arisan Sekolah · Giliran Sinta",
    amount: "Rp 100.000",
    due: "Sudah lewat jatuh tempo · 5 Jun",
    progress: 40,
    progressLabel: ["4/10 setor", "Putaran 4/10"],
    urgent: "Telat 3 hari",
    badgeLabel: "Arisan",
    ctaLabel: "Bayar Sekarang",
    ctaType: "pay",
    destName: "Dompet Grup Arisan Sekolah",
    destType: "arisan",
  },
  {
    id: "card5",
    type: "patungan",
    settled: true,
    eyebrow: "Patungan · Tiket Konser · 4 orang",
    amount: "Rp 800.000",
    due: "Semua sudah bayar",
    progress: 100,
    progressLabel: ["4/4 lunas", "Patungan"],
    badgeLabel: "Selesai",
    ctaLabel: "Kirim Bukti Transfer",
    ctaType: "proof",
    ctaVariant: "lv",
    ctaHint: "bagikan ke grup",
  },
  {
    id: "card6",
    type: "arisan",
    settled: true,
    eyebrow: "Arisan · Arisan Kompleks · 12 anggota",
    amount: "Rp 2.400.000",
    due: "Putaran 3 selesai · semua lunas",
    progress: 100,
    progressLabel: ["12/12 lunas", "Putaran 3/12"],
    badgeLabel: "Selesai",
    ctaLabel: "Kirim Bukti Transfer",
    ctaType: "proof",
    ctaVariant: "em",
    ctaHint: "ke Dompet Grup",
  },
];
