// Mirror of supabase/schema.sql — keep in sync when migrating

export type PlatformRole = 'user' | 'super_admin';
export type GroupRole = 'member' | 'admin';
export type Frequency = 'weekly' | 'monthly';
export type GiliranMethod = 'random' | 'manual';
export type GroupStatus = 'active' | 'completed' | 'pending';
export type RoundStatus = 'upcoming' | 'active' | 'completed';
export type PaymentStatus = 'pending' | 'confirmed' | 'rejected';
export type Language = 'id' | 'en';

export type BillCategory =
  | 'food'
  | 'transport'
  | 'accommodation'
  | 'utilities'
  | 'entertainment'
  | 'shopping'
  | 'other';

export type SplitMethod = 'equal' | 'exact' | 'percentage' | 'shares';
export type BillStatus = 'open' | 'settled';
export type SettlementStatus = 'pending' | 'confirmed' | 'rejected';
export type RecurringFrequency = 'weekly' | 'monthly' | 'yearly';
export type DebtStatus = 'pending' | 'settled' | 'dismissed';

export type PlanSlug = 'free' | 'boss' | 'business';
export type BillingCycle = 'monthly' | 'yearly';
export type SubscriptionStatus = 'active' | 'cancelled' | 'expired' | 'past_due';
export type Gateway = 'xendit' | 'midtrans' | 'manual';
export type TransactionType =
  | 'subscription_new'
  | 'subscription_renewal'
  | 'subscription_upgrade'
  | 'in_app_payment';
export type TransactionStatus =
  | 'pending'
  | 'paid'
  | 'failed'
  | 'refunded'
  | 'expired';

export type NotificationType =
  | 'payment_due'
  | 'payment_confirmed'
  | 'payment_rejected'
  | 'giliran_announced'
  | 'member_joined'
  | 'round_completed'
  | 'bill_created'
  | 'bill_settled'
  | 'bill_reminder'
  | 'settlement_confirmed'
  | 'settlement_rejected';

export interface AuthUser {
  id: string;
  email?: string;
  platform_role: PlatformRole;
}

// ─────────────────────────────────────────────────
// PAYMENT METHODS (v1 JSONB object shape)
// ─────────────────────────────────────────────────

// NOTE: only e-wallets are supported for now. Bank transfer and QRIS are deferred
// (bank → until scale; QRIS → until the Phase-4 image upload is built). The
// account_number/holder_name/qris_image_path fields stay in the shape so either
// can be re-added without a data migration.
export type PaymentMethodType =
  | 'gopay'
  | 'ovo'
  | 'dana'
  | 'shopeepay'
  | 'linkaja';

/** v1 payment method object stored in users.payment_methods JSONB array */
export interface PaymentMethodV1 {
  id: string;               // "pm_<uuid>" — immutable, generated by backend
  type: PaymentMethodType;
  label: string;            // user-defined display name
  account_number: string | null;  // bank: 6-20 digits; null for e-wallet/qris
  holder_name: string | null;     // bank: account holder name; null for e-wallet/qris
  phone: string | null;           // e-wallet: phone number; null for bank/qris
  qris_image_path: string | null; // optional QRIS image path (Phase 4)
  is_primary: boolean;
  created_at: string;       // ISO 8601
  updated_at: string;       // ISO 8601
}

/** Masked version returned to group co-members (non-owner peers) */
export interface PaymentMethodV1Masked
  extends Omit<PaymentMethodV1, 'account_number' | 'phone' | 'updated_at'> {
  account_number: string | null;  // "••••XXXX" (last 4) or null
  phone: string | null;           // "••••XXXX" (last 4) or null
  // updated_at omitted from peer responses per PRD Section 6, endpoint 5 example
}
